# Generated by Django 3.1.4 on 2021-01-06 13:06

from django.db import migrations, models
import ozilanons.models.duyurudata
import ozilanons.models.zilmelodileri


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuyuruData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=200, null=True, verbose_name='Duyuru Metni')),
                ('mp3yolu', models.FilePathField(null=True, path=ozilanons.models.duyurudata.mp3_path, verbose_name='Melodi Yolu')),
                ('guncellendi', models.BooleanField(default=False, verbose_name='Zil Güncel')),
                ('zilaktif', models.BooleanField(default=True, verbose_name='Zil Aktif')),
            ],
            options={
                'db_table': 'cal_duyur',
            },
        ),
        migrations.CreateModel(
            name='ZilMelodi',
            fields=[
                ('melodi_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('melodiad', models.TextField(choices=[['ogr', 'Öğretmen Giriş Zili'], ['ilk', 'Öğenci Giriş Zili'], ['cik', 'Çıkış Zili'], ['istiklal', 'İstiklal Marşı']], max_length=200, unique=True, verbose_name='Melodi Adı')),
                ('yol', models.FilePathField(null=True, path=ozilanons.models.zilmelodileri.mp3_path, verbose_name='Melodi Yolu')),
            ],
            options={
                'db_table': 'melodipath',
            },
        ),
    ]
